kind: PersistentVolume
apiVersion: v1
metadata:
  name: otus-pv-db-month2-lesson8
  namespace: m
  labels:
    app: otus-month2-lesson8
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/db
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: otus-pvc-db-month2-lesson8
  namespace: m
  labels:
    app: otus-month2-lesson8
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
