kind: Secret
apiVersion: v1
metadata:
  name: {{ print .Release.Name "-db-secret" | quote }}
  namespace: {{ .Values.namespace | quote }}
  annotations:
    # Note that if there is no such comment below, the current job will be treated as part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  POSTGRES_DB: b3R1cw==
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzcw==
  PGDATA: L2RhdGEvcGdkYXRh
