apiVersion: v1
kind: Service
metadata:
  name: otus-svc-month2-lesson7
  namespace: m
spec:
  selector:
    app: otus-month2-lesson7
  ports:
    - protocol: TCP
      port: 7999
      targetPort: 8000
  type: ClusterIP
