kind: Job
apiVersion: batch/v1
metadata:
  name: {{ print .Release.Name "-init-db-job" | quote }}
  namespace: {{ .Values.namespace | quote }}
  annotations:
    # Note that if there is no such comment below, the current job will be treated as part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    #"helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init-db-job
          image: {{ print .Values.db.image.repository ":" .Values.db.image.tag | quote }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ print .Release.Name "-db-secret" | quote }}
            - configMapRef:
                name: {{ print .Release.Name "-configmap" | quote }}
          command: ["psql"]
          args:
            - -Atq
            - {{ .Values.db.connectionString }}
            {{- $files := .Files }}
            {{- range tuple "db-scripts/create-table.sql" "db-scripts/init-users.sql" }}
            - c
            - {{ $files.Get . -}}
            {{- end }}
