namespace: "m"

ttlSecondsAfterFinished: 120

db:
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  port: 5432
  connectionString: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)
