kind: Job
apiVersion: batch/v1
metadata:
  name: {{ print .Release.Name "-init-db-job" | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  backoffLimit: 10
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init-db-job
          image: {{ print .Values.db.image.repository ":" .Values.db.image.tag | quote }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          {{- $appName := .Values.app | required "APP name is required!" }}
          envFrom:
            - secretRef:
                name: {{ print $appName "-db-secret" | quote }}
            - configMapRef:
                name: {{ print $appName "-configmap" | quote }}
          command: ["psql"]
          args:
            - -Atq
            - {{ .Values.db.connectionString }}
            {{- $files := .Files }}
            {{- range tuple "db-scripts/create-table.sql" "db-scripts/init-users.sql" }}
            - -c
            - {{ $files.Get . | trim | quote }}
            {{- end }}
